config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'search', to: 'search#index'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  root 'homes#home'

  resources :job_seekers, except: %i[new]
  resources :vacancys, except: %i[new]
  resources :companys

  get 'homes/firstpage'
  get 'homes/userhome'
  get 'homes/about'
  get 'homes/home2'
  get 'homes/blog1'
  get 'homes/blog2'
  get 'homes/blog3'

  get '/vacancys/new/:id', to: 'vacancys#new', as: 'new_vacancy'
  get '/job_seekers/new/:id1/:id2', to: 'job_seekers#new', as: 'new_job_seeker'
  get 'vacancys/jobshow/:id', to: 'vacancys#jobshow', as: 'vacancys_job'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
end

app/models/vacancy.rb
# frozen_string_literal: true

class Vacancy < ApplicationRecord
  belongs_to :company
  has_many :job_seekers
  validates :job_title, :job_type, :qualification, :language_knowledge, :experience, :skills, :description,
            presence: true
end

app/controllers/vacancys_controller.rb
# frozen_string_literal: true

class VacancysController < ApplicationController
  before_action :set_vs, only: %i[edit update show destroy]
  before_action :authenticate_user!

  def new
    @vs = Vacancy.new
  end

  def index
    @vs = Vacancy.all
  end

  def jobshow
    @js = Vacancy.find(params[:id]).job_seekers
  end

  def show; end

  def edit; end

  def create
    @vs = Vacancy.new(vs_params)
    authorize @vs

    if @vs.save
      flash[:notice] = 'successfully filled.'
      redirect_to @vs
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def update
    if @vs.update(vs_params)
      authorize @vs

      flash[:notice] = 'Sucessfully Updated'
      redirect_to @vs
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    @vs.destroy
    redirect_to vacancys_path
  end

  private

  def vs_params
    params.require(:vacancy).permit(:job_title, :job_type, :language_knowledge, :skills, 
                                    :qualification, :experience, :description, :company_id)
  end

  def set_vs
    @vs = Vacancy.find(params[:id])
  rescue ActiveRecord::RecordNotFound => e
    redirect_to vacancys_path
    flash[:notice] = e
  end
end

app/helpers/vacancys_helper.rb
# frozen_string_literal: true

module VacancysHelper
end

app/views/vacancys/_form.html.erb
 <%= form_with scope: :vacancy, url: vacancys_path, local: true do |f| %>

    <% if @vs.errors.any? %>
        <h2 class="er">The following errors prevented the vacancy being saved</h2>
        <% @vs.errors.full_messages.each do |msg| %>
        <p class="er"><%= msg %></p>
        <% end %>
    <% end %> 
    
    <p> 
        <%= f.label :job_title, class: 'mb-2'  %>
        <%= f.text_field :job_title, Placeholder: "Enter Job Title", autofocus: true,class: "form-control form-control-lg" %>
    </p>

    <p> 
        <%= f.label :job_type, class: 'mb-2'  %>
        <%= f.text_field :job_type, Placeholder: "like WFH, WFO", autofocus: true, class: "form-control form-control-lg" %>
    </p>

    <p> 
        <%= f.label :experience, class: 'mb-2'  %>
        <%= f.text_field :experience, Placeholder: "Enter Experience", autofocus: true, class: "form-control form-control-lg" %>
    </p>

    <p> 
        <%= f.label :qualification,  class: 'mb-2'  %>
        <%= f.text_field :qualification, Placeholder: "Enter qualification", autofocus: true, class: "form-control form-control-lg" %>
    </p>

    <p> 
        <%= f.label :language_knowledge,"language knowledge*", class: 'mb-2'  %>
        <%= f.text_field :language_knowledge, Placeholder: "Enter language", autofocus: true, class: "form-control form-control-lg" %>
    </p>
    
    <p> 
        <%= f.label :skills,  class: 'mb-2'  %>
        <%= f.text_field :skills, Placeholder: "Enter skills", autofocus: true, class: "form-control form-control-lg" %>
    </p>
   
    

    <p> 
        <%= f.label :description,  class: 'mb-2'  %>
        <%= f.text_field :description, Placeholder: "Enter description", autofocus: true, class: "form-control form-control-lg" %>
    </p>

    <p> 
        <%= f.hidden_field :company_id, value: params[:id], class: "form-control form-control-lg" %>
    </p>

    
    <p>
        <%= f.submit 'submit', class: "btn btn-primary" %> 
    </p>
    
 <% end %>

app/views/vacancys/_post.html.erb
<% @vs.each do |vacancy| %>

<div class="card tab border-info mb-2" style="max-width: 50rem;">
  <div class="card-body">
    <div class="card-header bg-transparent border-success">
      <h5 class="card-title"><%= vacancy.company.name %>, <%= vacancy.company.location %></h5>
      <p><%= vacancy.job_title %></p>
      <span style="color:blue;">Posted: <%= vacancy.created_at.strftime('%d/%m/%Y')%> | <%= vacancy.job_type %> | Jobs For COVID-19 Layoffs</span>
      <button><%= link_to "apply", new_job_seeker_path%></button>
    </div>
    <p>You can visit for more information about Company
      <a href="<%= vacancy.company.link %>"> Visit Webkorps.com!</a>
    </p>
    <p class="card-text">
      <h5 class="card-title">Minimum qualifications:</h5>
      <p class="card-text">
        <ul>
        <li><%= vacancy.qualification %></li>
        <li><%= vacancy.qualification %></li>
        <li><%= vacancy.language_knowledge %></li>
        </ul>
      </p>
    </p>
    <p>
      <span data-toggle="collapse" data-target="#collapseExample<%=vacancy.id%>" aria-expanded="false" aria-controls="collapseExample"><a>Expand↓</a></span>
    </p>
    <div class="collapse" id="collapseExample<%=vacancy.id%>">
      <div class="body">


    <h5>Preferred qualifications:</h5>
        <p>
            <ul>
            <li><%= vacancy.experience %></li>
            <li><%= vacancy.skills %></li>
            </ul>
        </p>

        <h3>About the job</h3>
        <div>
          <%= vacancy.description %>
        </div>
        <button><%= link_to 'Apply', new_job_seeker_path %></button>
          </div>
        </div> 
      </div>
    </div>

    <%end%>

app/views/vacancys/edit.html.erb
  <div class= "col-lg-6 mx-lg-auto form-border" style="margin: 20px;" >
      <div class="card-header bg-white text-black">
        <h2 class="card-title" >Edit Details</h2>
      </div>  
      <div class="card-body bg-white text-white">
            <%= form_with(model: @vs,  local: true) do |f| %>

            <% if @vs.errors.any? %>
                <h2 class="er">The following errors prevented the vacancy being saved</h2>
                <% @vs.errors.full_messages.each do |msg| %>
                <p class="er"><%= msg %></p>
                <% end %>
            <% end %> 
            
            <p> 
                <%= f.label :job_title, class: 'mb-2'  %>
                <%= f.text_field :job_title, Placeholder: "Enter Job Title", autofocus: true, class: "form-control form-control-lg" %>
            </p>

            <p> 
                <%= f.label :experience, class: 'mb-2'  %>
                <%= f.text_field :experience, Placeholder: "Enter Experience", autofocus: true, class: "form-control form-control-lg" %>
            </p>

            <p> 
                <%= f.label :qualification,  class: 'mb-2'  %>
                <%= f.text_area :qualification, Placeholder: "Enter qualification", autofocus: true, class: "form-control form-control-lg" %>
            </p>

            <p> 
                <%= f.label :description,  class: 'mb-2'  %>
                <%= f.text_area :description, Placeholder: "Enter description", autofocus: true, class: "form-control form-control-lg" %>
            </p>

            <p> 
                <%= f.label :company_id,  class: 'mb-2'  %>
                <%= f.text_field :company_id, class: "form-control form-control-lg" %>
            </p>

            
            <p>
                <%= f.submit 'submit', class: "btn btn-primary" %> 
            </p>
            
        <% end %>

      </div>
</div>  

app/views/vacancys/index.html.erb
<body>
<div class="container mt-5">
  <table class="table table-sm">
    <thead >
      </tr>
        <th>Job Title</th>
        <th>Time</th>
        <th colspan= "4">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @vs.each do |vacancy| %>
      
        <% if current_user.admin? || ( current_user.company? && current_user.id == vacancy.company.user_id ) %>
          <tr>
            <td><%= vacancy.job_title %></td>
            <td><%= formatted_date(vacancy.created_at) %></td>
            <td><%= link_to 'Show', vacancy_path(vacancy), class: "btn btn-primary" %></td>
            <td><%= link_to 'Delete', vacancy_path(vacancy),data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-primary" %></td>
            <td><%= link_to 'Edit', edit_vacancy_path(vacancy), class: "btn btn-primary" %></td> 
            <td><%= link_to 'Request', vacancys_job_path(vacancy), class: "btn btn-primary" %></td>
          </tr>
        <% end %>
      <% end %>

     </tbody>
  </table>
</div>
</body>


        <%
=begin%>
            <td><button><%= link_to 'All Filled Form', job_seekers_path(vacancy.id) %></button></td>

 <th>Company Detail Id%</th>
        <td><%= vacancy.company_detail_id %></td> 
<%
=end%>

app/views/vacancys/jobshow.html.erb
<body>
<div class="container mt-5">
  <table class="table table-sm">
    <thead>
      </tr>
        <th>Name</th>
        <th>Number</th>
        <th>Email</th>
        <th colspan= "3">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @vs.each do |seeker| %>
    
        <tr>
          <td><%= seeker.name %></td>
          <td><%= seeker.number %></td>
          <td><%= seeker.email %></td>
          <td><button><%= link_to 'Show', job_seeker_path(seeker) %></button>
          <td><button><%= link_to 'Delete', job_seeker_path(seeker),data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %></button></td>
          <td><button><%= link_to 'Edit', edit_job_seeker_path(seeker) %></button></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  </div>
</body>

app/views/vacancys/new.html.erb
  <div class= "col-lg-6 mx-lg-auto form-border" style="margin: 20px;" >
      <div class="card-header bg-white text-black">
        <h2 class="card-title" >Enter Details</h2>
      </div>  
      <div class="card-body bg-white text-white">
        <%= render "form" %>
      </div>
    
  </div>

app/views/vacancys/show.html.erb
<div class= "col-lg-6 mx-lg-auto">
  <div class="card shadow">
    <div class="card-header">
    <h2 class="card-title">vacancy</h2>
    </div>
    <div class="card-body">
      <p><strong>job_title: </strong><%= @vs.job_title %></p>
      <p><strong>job_type: </strong><%= @vs.job_type %></p>
      <p><strong>experience: </strong><%= @vs.experience %></p>
      <p><strong>qualification: </strong><%= @vs.qualification %></p>
      <p><strong>skills: </strong><%= @vs.skills %></p>
      <p><strong>language knowledge: </strong><%= @vs.language_knowledge %></p>
      <p><strong>description: </strong><%= @vs.description %></p>
      <p><strong>company_id: </strong><%= @vs.company_id %></p>
  </div>
</div>