config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'search', to: 'search#index'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  root 'homes#home'

  resources :job_seekers, except: %i[new]
  resources :vacancys, except: %i[new]
  resources :companys

  get 'homes/firstpage'
  get 'homes/userhome'
  get 'homes/about'
  get 'homes/home2'
  get 'homes/blog1'
  get 'homes/blog2'
  get 'homes/blog3'

  get '/vacancys/new/:id', to: 'vacancys#new', as: 'new_vacancy'
  get '/job_seekers/new/:id1/:id2', to: 'job_seekers#new', as: 'new_job_seeker'
  get 'vacancys/jobshow/:id', to: 'vacancys#jobshow', as: 'vacancys_job'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
end

app/controllers/homes_controller.rb
# frozen_string_literal: true

# home controller
class HomesController < ApplicationController
  def home; end

  def firstpage; end

  def userhome
    @user = User.all
  end

  def home2
    @vs = Vacancy.all
  end

  def blog1; end

  def blog2; end

  def blog3; end

  def about; end
  
end

app/helpers/homes_helper.rb
# frozen_string_literal: true

module HomesHelper
end

app/views/homes/_about.html.erb
<section id="about" class="job py-5">
  <div class="container py-5">
    <div class="row py-5">
      <div class="col-lg-7">
        <p class="red pt-5">WHAT WE ARE DOING</p>
        <h1>24K Talented prople are getting Jobs</h1>
        <p class="py-4" style="font-weight: 700;">Online job pitara are beneficial.
         The job pitara helps in automating the recruitment process. That's why many
          organisations use their job pitara. These are an effective way to connect the
           job seekers with recruiters, and it also helps the recruiters to attract more 
           candidates.</p>
           <p>A job pitara app is a feature-rich platform integrated with advanced job 
           facilitation resources that allows job seekers to connect with companies, firms 
           & agencies that are recruiting and vice versa. Searching for a job is one of the 
           most frustrating and challenging things we all have experienced.</p>
      </div>
      <div class="col-lg-5">
          <%= image_tag "about.jpg", class: "img-fluid", alt:""  %>
      </div>
    </div>
  </div>
</section>

app/views/homes/_post.html.erb
<% @vs.each do |vacancy| %>

  <div class="card  tab border-info mb-2 my-2 " style="max-width: 40rem;">
    <div class="card-body">
      <div class="card-header bg-transparent border-success">
        <h5 class="card-title"><%= vacancy.company.name %>, <%= vacancy.company.location %></h5>
        <p><%= vacancy.job_title %></p>
        <span style="color:blue;">Posted: <%= vacancy.created_at.strftime('%d/%m/%Y')%> | <%= vacancy.job_type %> | Jobs For COVID-19 Layoffs</span>
        <%= link_to "apply", new_job_seeker_path(vacancy.id,vacancy.company_id), class: "btn btn-primary"%>
      </div>
      <p>You can visit for more information about Company
        <a href="<%= vacancy.company.link %>"> Click!</a>
      </p>
      <p class="card-text">
        <h5 class="card-title">Minimum qualifications:</h5>
        <p class="card-text">
          <ul>
          <li><%= vacancy.qualification %></li>
          <li><%= vacancy.language_knowledge %></li>
          </ul>
        </p>
      </p>
      <p>
        <span data-toggle="collapse" data-target="#collapseExample<%=vacancy.id%>" aria-expanded="false" aria-controls="collapseExample" style="color:blue;">Expand↓</span>
      </p>
      <div class="collapse" id="collapseExample<%=vacancy.id%>">
        <div class="body">


      <h5>Preferred qualifications:</h5>
      <p>
        <ul>
        <li><%= vacancy.experience %></li>
        <li><%= vacancy.skills %></li>
        </ul>
      </p>

      <h3>About the job</h3>
      <div>
        <%= vacancy.description %>
      </div>
      <%= link_to 'Apply', new_job_seeker_path(vacancy.id,vacancy.company_id), class: "btn btn-primary"   %>
        </div>
      </div> 
    </div>
  </div>

<%end%>

app/views/homes/about.html.erb
<%= render "about" %>

app/views/homes/blog1.html.erb
<div class=" container py-5">
<h1>How To Enjoy Work</h1>
<p>The Indeed Editorial Team comprises a diverse and talented team of writers, researchers and subject matter experts equipped with Indeed's data and insThe Indeed Editorial Team comprises a diverse and talented team of writers, researchers and subject matter experts equipped with Indeed's data and insights to deliver useful tips to help guide your career journey.ights to deliver useful tips to help guide your career journey.</p>
<p>There are many people who are happy with their work, especially if they are in a job that matches their career and life goals. However, even with the best job, there are times when you struggle to find enjoyment in what you are doing. During times of stress or discouragement, finding that joy in work can be difficult. In this article, we will consider why enjoying your job is important and look at some ways you can rediscover the joy in your work.
</p>
<h2>Why it's important to enjoy work</h2>
<p>While you have other things in your life besides work such as friends, family, and hobbies, working is a large part of what you do every week. This is one reason why you should find ways to enjoy your work.<p>
<p>Also, your attitude toward work will affect your mood. If you struggle to find the motivation to go to work and resent the time you are there when you could be elsewhere, you will cultivate a negative attitude that spills over into the rest of your life. It can affect your performance at work, as well as your relationships with co-workers, friends and family.
</p>
<h2>How to enjoy work</h2>
<p>One way to find enjoyment in your work is to look for employment that is compatible with your life and career goals. If your current job is not in alignment with what you most enjoy doing, you are going to be more easily discouraged and dissatisfied with your work. Looking for work that will bring you satisfaction and fulfillment can help you enjoy your job. Here are some tips and strategies to help you increase your enjoyment of work:
</p>
<h4>1. Take breaks</h4>
<p>During a busy workday, it is important you take time away from your desk to get your mind off your job. Schedule a lunch break on your calendar every day and keep it. Even five minutes spent outside if the weather's good, or sitting in the break room, can be good for your mental health and perspective. When you take these breaks, leave your cell phone on your desk. Detach from work completely so you can return refreshed.
</p>
<h4>2. Manage your workspace
</h4>
<p>If your workspace, whether an office or a cubicle, is a mess, tidy it. Throw away anything you don't have to keep. If you have a physical inbox, make sure it only contains things you have yet to do. A clean and organized workspace can help you feel more relaxed and in control of your environment.
</p>
<h4>3. Enjoy the people you work with</h4>
<p>Find ways to have fun in your workplace while maintaining a professional approach to your work. Smile and engage with your co-workers. Get to know them, perhaps even socially outside of work. If you enjoy spending time with the people you work with, this can go a long way toward making your work more enjoyable.
</br>
A positive attitude toward your co-workers can also help you cultivate a positive attitude toward your work. One way to express this is to avoid office gossip and, instead, engage in constructive conversations that encourage your co-workers.
</p>
<h4>4. Upgrade your skills</h4>
<p>Lack of enjoyment in your work might be a sign that you don't find your work challenging enough. You may need to consider personal development so you can take your career to the next level. Find out what training you need in order to progress. If you work in IT, or another field that is constantly changing, you may need to update your skills. In this case, you should investigate classes or appropriate coursework that will keep your skills current and challenge you.

</p>
<h4>5. Accept the imperfect</h4>
<p>It's possible you're feeling frustrated with your co-workers and managers because they do not perform to your expectations. In this case, you need to remember that no-one is perfect, and working with people means working with people who make mistakes and have bad days, just like you. Wherever you work, there will be managers who frustrate you, co-workers who miss deadlines, and projects that don't go to plan. The sooner you can accept the imperfect, the sooner you can manage your frustrations and focus on your work.</p>
</div>

app/views/homes/blog2.html.erb
<h1 class="blog-h1 py-5">Top 10 Tips for a Job Interview</h1>
<%= image_tag "blog2.jpg", class: "blog2-image" %>
<div class=" container blog22">
<h3>1) Research the company</h3>
<h3>2) Predict the job interview questions and prepare answers</h3>
<h3>3) Dress suitably</h3>
<h3>4) Arrive a little early</h3>
<h3>5) Make a good first impression</h3>
<h3>6) Be calm, confident, positive, and focused</h3>
<h3>7) Don’t be modest, sell yourself</h3>
<h3>7) Don’t be modest, sell yourself</h3>
<h3>9) Make a good final impression</h3>
<h3>10) Follow-up</h3>
</div>

app/views/homes/blog3.html.erb
<h1 class="blog-h1">Time Management</h1>
<p class="pp">Planning and controlling how much time to spend on specific activities</p>
<div class=" container blog21">
<h3>A Brief Guide to Time Management</h3>
<p>Time management is the process of planning and controlling how much time to spend on specific activities. Good time management enables an individual to complete more in a shorter period of time, lowers stress, and leads to career success.</p>
</div>
<%= image_tag "blog3.png", class: "blog2-image" %>
<div class=" container blog22">
<h3>Benefits of Time Management</h3>
<p>The ability to manage your time effectively is important. Good time management leads to improved efficiency and productivity, less stress, and more success in life. Here are some benefits of managing time effectively:
</p>
<h4>1. Stress relief</h4>
<p>Making and following a task schedule reduces anxiety. As you check off items on your “to-do” list, you can see that you are making tangible progress. This helps you avoid feeling stressed out with worry about whether you’re getting things done.</p>
<h4>2. More time</h4>
<p>Good time management gives you extra time to spend in your daily life. People who can time-manage effectively enjoy having more time to spend on hobbies or other personal pursuits.</p>
<h4>3. More opportunities</h4>
<p>Managing time well leads to more opportunities and less time wasted on trivial activities. Good time management skills are key qualities that employers look for. The ability to prioritize and schedule work is extremely desirable for any organization.<p>
<h4>4. Ability to realize goals</h4>
<p>Individuals who practice good time management are able to better achieve goals and objectives, and do so in a shorter length of time.</p>
<h4>5. Poor reputation</h4>
<p>If clients or your employer cannot rely on you to complete tasks in a timely manner, their expectations and perceptions of you are adversely affected. If a client cannot rely on you to get something done on time, they will likely take their business elsewhere.</p>
</dov>

app/views/homes/firstpage.html.erb
<body>
  <div  class="bi">
    <div class="cent">
      <div class='main_content'>
        <div>
          <h1 class="main_head">
          <span class="f1-text">Your Dream</span> <span class="f2-text"> Job Is Waiting </span></br>
          <%= link_to "CLICK", root_path, class: "btn btn-primary" %>
          </h1>

        </div>
      </div>
    </div>
  </div>
</body>

app/views/homes/home.html.erb
<section class="main py-5">
  <div class="container py-5">
    <div class="row">
      <div class="col-lg-7">
        <h1>Find The <br> Most Exciting <br>
        Startup Jobs</h1>

        <%= search_form_for(@query, url: search_path, method: :get) do |f| %>
            <%= f.search_field :job_title_or_job_type_i_cont_any, placeholder: "Job Tttle Or Type.....", class: "in" %>
            <%= f.submit "Find Job", class: "btn2 mt-2"  %>
        <% end %>
        
      </div>
    </div>
  </div>
</section> 

<%= render "about" %>

<section class="apply py-5">
  <div class="container text-white text-center py-5">
    <p class="red">APPLY PROCESS</p>
    <h1 >How it work</h1>
    <div class="row" py-5>

      <div class="col-lg-4 pt-2">
        <a href="http://localhost:3000/search"><div class="card p-3">
          <div class="card-body text-center">
            <div class="cir1 pt-3 mb-3">
              <%= image_tag "Cate1.JPG", class: "img-fluid", alt:""  %>
            </div>
            <h2>Search a job</h2>
            <p class="py-3">From applying to jobs to following up after an interview,
             here everything <p>
          </div>
        </div></a>
      </div>

      <div class="col-lg-4 pt-2">
        <a href="http://localhost:3000/homes/home2"><div class="card p-3">
          <div class="card-body text-center">
            <div class="cir1 pt-3 mb-3">
              <%= image_tag "cate4.JPG", class: "img-fluid", alt:""  %>
            </div>
            <h2>Apply for job</h2>
            <p class="py-3">From applying to jobs to following up after an interview,
             here everything <p>
          </div>
        </div></a>
      </div>

      <div class="col-lg-4 pt-2">
        <a href="http://localhost:3000/homes/home2"><div class="card p-3">
          <div class="card-body text-center">
            <div class="cir1 pt-3 mb-3">
              <%= image_tag "cate5.JPG", class: "img-fluid", alt:""  %>
            </div>
            <h2>Get your job</h2>
            <p class="py-3">From applying to jobs to following up after an interview,
             here everything <p>
          </div>
        </div></a>
      </div>

    </div>
  </div>
</section>

<section class="blog" id="blog">
  <h1 calss="section-title">Career Advices</h1>
  <p>Learn more career tips from company's recruiter</p>
  <div class="blog-wrapper">

    <a href="<%= homes_blog1_path %>" class="blog-href">
    <div class="blog-card">
      <%= image_tag "first1.png", class: "blog-image" %>
      <div class="blog-detail">
        <span>11 Apr 2022</span>
        <h4>How to enjoy your work</h4>
        <p> One way to find enjoyment in your work is to look for employment that is compatible with your life and career goals</p>
        <hr class="divider">
        <a href="<%= homes_blog1_path %>" class="blog-more">Read more</a>
      </div>
    </div></a>

    <a href="<%= homes_blog2_path %>" class="blog-href"><div class="blog-card">
      <%= image_tag "blog2.jpg", class: "blog-image" %>
      <div class="blog-detail">
        <span>11 May 2022</span>
        <h4>10 Tips for technical interview</h4>
        <p> Job interview preparation: Doing your homework on the employer is the foundation to a successful interview. </p>
        <hr class="divider">
        <a href="<%= homes_blog2_path %>"" class="blog-more">Read more</a>
      </div>
    </div></a>

    <a href="<%= homes_blog3_path %>" class="blog-href"><div class="blog-card">
      <%= image_tag "blog5.jpeg", class: "blog-image" %>
      <div class="blog-detail">
        <span>11 Jun 2022</span>
        <h4>Managing Time Effectively</h4>
        <p> Time management is the process of planning and controlling how much time to spend on specific activities.</p>
        <hr class="divider">
        <a href="<%= homes_blog3_path %>" class="blog-more">Read more</a>
      </div>
    </div></a>

  </div>
<section >
</section>

<section class="slider py-5">
  <div class="container text-center py-5">
    <div class="row">
      <div class="col-lg-9 m-auto">
        
        <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
          <div class="carousel-inner">
          
            <div class="carousel-item active">
              <%= image_tag "Capture.JPG", class: "img-fluid avatar mb-4", alt:"..."  %>
              <h4>Mergaret Lawson</h4>
              <p>Creative Director</p>
              <p class="perac py-3">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled</p>
            </div>

            <div class="carousel-item">
              <%= image_tag "car2.JPG", class: "img-fluid avatar mb-4", alt:"..."  %>
              <h4>Mergaret Lawson</h4>
              <p>Creative Director</p>
              <p class="perac py-3">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled</p>
           
            </div>

            <div class="carousel-item">
              <%= image_tag "car2.JPG", class: "img-fluid avatar mb-4", alt:"..."  %>
              <h4>Mergaret Lawson</h4>
              <p>Creative Director</p>
              <p class="perac py-3">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled</p>
           
            </div>

          </div>
          <%
=begin%>
 <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button> 
<%
=end%>
        </div>

      </div>
    </div>
  </div>
</section>

<%
=begin%>
 
<section class="ceta py-5">
  <div calss="container-fluid py-5 text-center">
    <p class="red">FEATURED TOURS PACKAGES</P>
    <h1>Browse Top Categories</h1>
    <div class="row py-5">
      <div class="col-lg-11 m-auto pt-3">
        <div class="row py-5">
        
          <div class="col-lg-3">
            <div class="card py-3">
              <div class="card-body">
                <%= image_tag "Cate1.JPG", class: "img-fluid my-3", alt:""  %>
                <h6>Design & Creative</h6>
                <h6 class="red">(785)</h6>
              </div>
            </div>
          </div>
          <div class="col-lg-3">
            <div class="card py-3">
              <div class="card-body">
                <%= image_tag "Cate1.JPG", class: "img-fluid my-3", alt:""  %>
                <h6>Design & Creative</h6>
                <h6 class="red">(785)</h6>
              </div>
            </div>
          </div>
          <div class="col-lg-3">
            <div class="card py-3">
              <div class="card-body">
                <%= image_tag "Cate1.JPG", class: "img-fluid my-3", alt:""  %>
                <h6>Design & Creative</h6>
                <h6 class="red">(785)</h6>
              </div>
            </div>
          </div>
          <div class="col-lg-3">
            <div class="card py-3">
              <div class="card-body">
                <%= image_tag "Cate1.JPG", class: "img-fluid my-3", alt:""  %>
                <h6>Design & Creative</h6>
                <h6 class="red">(785)</h6>
              </div>
            </div>
          </div>

          <div class="col-lg-3">
            <div class="card py-3">
              <div class="card-body">
                <%= image_tag "Cate1.JPG", class: "img-fluid my-3", alt:""  %>
                <h6>Design & Creative</h6>
                <h6 class="red">(785)</h6>
              </div>
            </div>
          </div>
          <div class="col-lg-3">
            <div class="card py-3">
              <div class="card-body">
                <%= image_tag "Cate1.JPG", class: "img-fluid my-3", alt:""  %>
                <h6>Design & Creative</h6>
                <h6 class="red">(785)</h6>
              </div>
            </div>
          </div>
          <div class="col-lg-3">
            <div class="card py-3">
              <div class="card-body">
                <%= image_tag "Cate1.JPG", class: "img-fluid my-3", alt:""  %>
                <h6>Design & Creative</h6>
                <h6 class="red">(785)</h6>
              </div>
            </div>
          </div>
          <div class="col-lg-3">
            <div class="card py-3">
              <div class="card-body">
                <%= image_tag "Cate1.JPG", class: "img-fluid my-3", alt:""  %>
                <h6>Design & Creative</h6>
                <h6 class="red">(785)</h6>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
</section> 
<%
=end%>



<section class="footer py-5">
  <div class="container-fluid py-5">
    <div class="row">
      <div class="col-lg-10 m-auto">
        <div class="row">
          <div class="col-lg-4">
            <h3 class="py-5">ABOUT US</h3>
            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. </p>
          </div>
          <div class="col-lg-4">
            <h3 class="py-5">CONTACT INFO</h3>
            <p>Address : Vijay nagar, Indore(MP)</p>
            <p class="link pt-3">Phone : +9340805774</p>
            <p class="link">Email : www.123@email.com</p>
          </div>
          <div class="col-lg-4">
            <h3 class="py-5">IMPORTANT LINK</h3>
            <p class="link">View Project</p>
            <p class="link">Contect Us</p>
            <p class="link">Testimonial</p>
            <p class="link">Properties</p>
            <p class="link">Support</p>
          </div
        </div>
        <hr>
        <p class="py-4">Copyright 02022 All rights reserved | This template is made with by <span class="red">ROR</span></p>
      </div>
    </div>
  </div>

</section>

app/views/homes/home2.html.erb
<% if user_signed_in? %>
    <div class="identity"> Hii <span><%= current_user.username%></span></br>
     you are a <span><%= current_user.role%></span></div>
<%end%> 
<%= render "homes/post"%>

app/views/homes/userhome.html.erb
<body>
<table class="table table-sm">
    <thead>
      </tr>
        <th>S.No</th>
        <th>Username</th>
        <th>Email</th>
        <th>Role</th>
      </tr>
    </thead>
    <tbody>
      <% s=1 %>
      <% @user.each do |user| %>
        <tr>
            <td><%= p s %></td>
            <% s+=1 %>
            <td><%= user.username %></td>
            <td><%= user.email%></td>
            <td><%=user.role%></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</body>