config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'search', to: 'search#index'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  root 'homes#home'

  resources :job_seekers, except: %i[new]
  resources :vacancys, except: %i[new]
  resources :companys

  get 'homes/firstpage'
  get 'homes/userhome'
  get 'homes/about'
  get 'homes/home2'
  get 'homes/blog1'
  get 'homes/blog2'
  get 'homes/blog3'

  get '/vacancys/new/:id', to: 'vacancys#new', as: 'new_vacancy'
  get '/job_seekers/new/:id1/:id2', to: 'job_seekers#new', as: 'new_job_seeker'
  get 'vacancys/jobshow/:id', to: 'vacancys#jobshow', as: 'vacancys_job'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
end

app/models/company.rb
# frozen_string_literal: true

class Company < ApplicationRecord
  has_one :vacancy
  has_many :job_seekers, dependent: :destroy
  belongs_to :user
  validates :name, :location, :started_year, :link, :job_types, presence: true
end

app/controllers/companys_controller.rb
# frozen_string_literal: true

# controller
class CompanysController < ApplicationController
  before_action :authenticate_user!
  before_action :set_cd, only: %i[edit update show destroy]

  def new
    @cd = Company.new
  end

  def index
    @cd = Company.all
  end

  def show; end

  def edit; end

  def create
    @cd = Company.new(cd_params)
    authorize @cd
    if @cd.save
      flash[:notice] = ' successfully Applied.'
      redirect_to @cd
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def update
    if @cd.update(cd_params)
      authorize @cd

      flash[:notice] = 'Sucessfully Updated'
      redirect_to @cd
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    authorize @cd
    @cd.destroy
    redirect_to companys_path
  end

  private

  def cd_params
    params.require(:company).permit(:name, :link, :location, :started_year, :job_types,
                                    :user_id)
  end

  def set_cd
    @cd = Company.find(params[:id])
  rescue ActiveRecord::RecordNotFound => e
    redirect_to companys_path
    flash[:notice] = e
  end
end

app/views/companys/_form.html.erb
 <%= form_with scope: :company, url: companys_path, local: true do |f| %>

    <p> 
        <%= f.label :name, class: 'mb-2'  %>
        <%= f.text_field :name, Placeholder: "Enter company name", autofocus: false, class: "form-control form-control-lg" %>
    </p>

    <p> 
        <%= f.label :link, class: 'mb-2'  %>
        <%= f.text_field :link, Placeholder: "Enter company name", autofocus: true, class: "form-control form-control-lg" %>
    </p>

    <p> 
        <%= f.label :location, class: 'mb-2'  %>
        <%= f.text_field :location, Placeholder: "Enter company location", autofocus: true, class: "form-control form-control-lg" %>


    </p>

    <p> 
        <%= f.label :started_year, class: 'mb-2'  %>
        <%= f.date_field :started_year, Placeholder: "Enter company started_year", autofocus: true, class: "form-control form-control-lg" %>
    </p>

    <p> 
        <%= f.label :job_types, class: 'mb-2'  %>
        <%= f.text_field :job_types, Placeholder: "Enter job_types", autofocus: true, class: "form-control form-control-lg"%>
    </p>

    <p> 
        <%= f.hidden_field :user_id, value: current_user.id %>
    </p>
  
    <p>
        <%= f.submit 'submit', class: "btn btn-primary" %> 
    </p>
    
    <% end %>

app/views/companys/edit.html.erb
  <div class= "col-lg-6 mx-lg-auto form-border" style="margin: 20px;">
      <div class="card-header bg-white text-black">
        <h2 class="card-title" >Enter Details</h2>
      </div>  
      <div class="card-body bg-white text-white">
     
        <%= form_with(model: @cd,  local: true) do |f| %>

            <% if @cd.errors.any? %>
                <h2 class="er">The following errors prevented the Company details being saved</h2>
                <% @cd.errors.full_messages.each do |msg| %>
                <p class="er"><%= msg %></p>
                <% end %>
            <% end %> 
              
            <p> 
                <%= f.label :name, class: 'mb-2'  %>
                <%= f.text_field :name, Placeholder: "Enter company name", autofocus: true, class: "form-control form-control-lg" %>
            </p>
            <p> 
                <%= f.label :link, class: 'mb-2'  %>
                <%= f.text_field :link, Placeholder: "Enter company name", autofocus: true, class: "form-control form-control-lg" %>
            </p>

            <p> 
                <%= f.label :location, class: 'mb-2'  %>
                <%= f.text_field :location, Placeholder: "Enter company location", autofocus: true, class: "form-control form-control-lg" %>
            </p>

            <p> 
                <%= f.label :started_year, class: 'mb-2'  %>
                <%= f.date_field :started_year, Placeholder: "Enter company started_year", autofocus: true, class: "form-control form-control-lg" %>
            </p>

            <p> 
                <%= f.label :job_types, class: 'mb-2'  %>
                <%= f.text_field :job_types, Placeholder: "Enter job_types", autofocus: true, class: "form-control form-control-lg"%>
            </p>

            <p> 
                <%= f.label :user_id, class: 'mb-2'  %>
                <%= f.number_field :user_id, class: "form-control form-control-lg"%>
            </p>
        
            <p>
                <%= f.submit 'submit', class: "btn btn-primary" %> 
            </p>
            
        <% end %>
    
  </div>
</div>  

app/views/companys/index.html.erb
<body>
<div class="container mt-5">
  <table class="table table-sm">
    <thead>
      </tr>
        <th>Company Name</th>
        <th>Location</th>
        <th>Started Year</th>
        <th>job Types</th>
        <th>user_id</th>
        <th colspan= "4">Actions</th>


      </tr>
    </thead>
    <tbody>
      <% @cd.each do |comp| %> 
      <% if current_user.admin? || ( current_user.company? && current_user.id == comp.user_id ) %>     
        <tr>
            <td><%= comp.name %></td>
            <td><%= comp.location %></td>
            <td><%= comp.started_year %></td>
            <td><%= comp.job_types %></td>
            <td><%= comp.user_id%></td>
            <td><%= link_to 'Show', company_path(comp), class: "btn btn-primary" %></td>
            <td><%= link_to 'Delete', company_path(comp),data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-primary" %></td>
            <td><%= link_to 'Edit', edit_company_path(comp), class: "btn btn-primary" %></td>
            <td><%= link_to 'Post.Vacancy', new_vacancy_path(comp.id), class: "btn btn-primary" %></td>
            <td><%= link_to 'All Vacancy', vacancys_path(comp.id), class: "btn btn-primary" %></td>

        </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>
</body>

app/views/companys/new.html.erb
<% if @cd.errors.any? %>
    <h4 class="er">The following errors prevented the Company details being saved</h4>
    <% @cd.errors.full_messages.each do |msg| %>
    <ul>
    <li class="er"> <%= msg %></li>
    </ul>
    <% end %>
<% end %> 

<div class= "col-lg-6 mx-lg-auto form-border" style="margin: 20px;">
  <div class="card-header bg-white text-black">
    <h2 class="card-title" >Enter Details</h2>
  </div>  
  <div class="card-body bg-white text-white">
    <%= render "form" %>
  </div>
</div>

<%
=begin%>
 <  <div class="form-border"> 
<%
=end%>

app/views/companys/show.html.erb
<div class= "col-lg-6 mx-lg-auto">
  <div class="card shadow">
    <div class="card-header">
    <h2 class="card-title">Company Details</h2>
    </div>
    <div class="card-body">
      <p><strong>Nacompany_nameme: </strong><%= @cd.name %></p>
      <p><strong>company_location: </strong><%= @cd.location %></p>
      <p><strong>company_started_year: </strong><%= @cd.started_year %></p>
      <p><strong>job_types: </strong><%= @cd.job_types %></p>
      <p><strong>user_id: </strong><%= @cd.user_id %></p>
      <%= link_to "See Company Details", companys_path , class: "taxt-center"%>

  </div>
</div>